apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    name: front
spec:
  containers:
    - name: web
      image: samargooda/python-challenge-app:1
      ports:
        - containerPort: 8000
      env:
        - name: ENVIRONMENT
          value: "DEV"
        - name: HOST
          value: "localhost"
        - name: PORT
          value: "8000"
        - name: REDIS_HOST
          value: "service"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
