apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    name: front-db
  type: ClusterIP
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 6379
      targetPort: 6379
      
